project_id = "oltleppgnjmxggentltm"

[functions.google-data]
verify_jwt = true

[functions.planning-chat]
verify_jwt = true

[functions.save-schedule]
verify_jwt = true

[functions.enrich-library-item]
verify_jwt = true
