project_id = "oltleppgnjmxggentltm"

[functions.google-data]
verify_jwt = false

[functions.planning-chat]
verify_jwt = false

[functions.save-schedule]
verify_jwt = false

[functions.sync-completed-tasks]
verify_jwt = false

[functions.enrich-library-item]
verify_jwt = false
